# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab3dbc80705a861006b03e9390592d9e4908f270223beb662ca0056f285033880ae6ff5fec61e01d7b8c3c85472ac4e1f4dda9ee886bd02df6234fc8640ae391

test:
  secret_key_base: 621238cf2baa68406a7e5037940036fef4455ca19c808cbf8e8c394c09a335458a7d93758e9a14c384d96d5a9d862b93fdfb0a2b975cd6e16fba89271b0afc98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
